import {ReactNode} from 'react';

import NavBar from '@/modules/Navbar/Navbar';
import type {Metadata} from 'next';
import {Open_Sans, Unbounded} from 'next/font/google';

import './globals.css';
import Providers from "@/app/providers";

const unbounded = Unbounded({
    variable: '--font-unbounded',
    subsets: ['latin', 'cyrillic'],
});

const openSans = Open_Sans({
    variable: '--font-open-sans',
    subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="manifest" href="/manifest.json"/>
            <meta name="theme-color" content="#3e01db"/>
            <title></title>
        </head>
        <body
            className={`${unbounded.variable} ${openSans.variable} px-4 antialiased`}
        >
        <main className={'mx-auto mb-28 max-w-3xl'}><Providers>{children}</Providers></main>
        <NavBar></NavBar>
        </body>
        </html>
    );
}
