CREATE TABLE "reports_history" (
  "report_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES users(user_id),
  "log_datetime" timestamp DEFAULT (now()),
  "report" text NOT NULL
);

CREATE INDEX "idx_reports_id" ON "reports_history" ("report_id");

CREATE INDEX "idx_reports_user_id" ON "reports_history" ("user_id");

CREATE INDEX "idx_reports_datetime" ON "reports_history" ("log_datetime");

CREATE INDEX "idx_reports_user_datetime" ON "reports_history" ("user_id", "log_datetime");

COMMENT ON TABLE "reports_history" IS 'История AI-отчетов для пользователей';