CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX "idx_users_id" ON "users" ("user_id");

CREATE INDEX "idx_users_email" ON "users" ("email");

COMMENT ON TABLE "users" IS 'Таблица пользователей';