package repository

import (
	"aura/internal/models"
	"context"
	"fmt"
	"time"

	sq "github.com/Masterminds/squirrel"
	"github.com/jackc/pgx/v5/pgxpool"
)

type ThoughtsRepo struct {
	db *pgxpool.Pool
}

func NewThoughtsRepo(db *pgxpool.Pool) *ThoughtsRepo {
	return &ThoughtsRepo{db: db}
}

func (r *ThoughtsRepo) CreateThought(ctx context.Context, req *models.CreateThoughtReq) (*models.Thought, error) {
	createdAt := time.Now()
	if req.CreatedAt != nil {
		createdAt = *req.CreatedAt
		println(fmt.Sprintf("[CreateThought] Using custom created_at: %v", createdAt))
	} else {
		println(fmt.Sprintf("[CreateThought] Using current time: %v", createdAt))
	}
	// thought_id is auto-generated by DB (BIGSERIAL), don't include it in INSERT
	// Use only fields that exist in DB schema: user_id, created_at, content, voice_text, sentiment_label, sentiment_score, type_thought, minio_id
	sql, args, _ := QB.Insert("thoughts").
		Columns("user_id", "created_at", "content", "voice_text", "sentiment_label", "sentiment_score", "type_thought", "minio_id").
		Values(req.UserID, createdAt, req.Content, req.VoiceText, req.SentimentLabel, req.SentimentScore, req.TypeThought, req.ImageID).
		Suffix("RETURNING thought_id, user_id, created_at, content, voice_text, sentiment_label, sentiment_score, type_thought, minio_id").ToSql()

	println(fmt.Sprintf("[CreateThought] SQL: %s", sql))
	println(fmt.Sprintf("[CreateThought] Args: user_id=%d, created_at=%v, content=%v", req.UserID, createdAt, req.Content))
	
	var thought models.Thought
	var content *string
	var voiceText *string
	var typeThought *string
	var minioID *string

	err := r.db.QueryRow(ctx, sql, args...).Scan(
		&thought.ThoughtID,
		&thought.UserID,
		&thought.CreatedAt,
		&content,
		&voiceText,
		&thought.SentimentLabel,
		&thought.SentimentScore,
		&typeThought,
		&minioID,
	)
	if err != nil {
		println(fmt.Sprintf("[CreateThought] DB Error: %v", err))
		return nil, err
	}

	println(fmt.Sprintf("[CreateThought] Successfully created thought_id=%d with created_at=%v", thought.ThoughtID, thought.CreatedAt))
	
	thought.Content = content
	thought.VoiceText = voiceText
	thought.TypeThought = typeThought
	thought.ImageID = minioID // Map minio_id from DB to ImageID in model
	// Set optional fields to nil (not in DB schema)
	thought.SubmittedAt = nil
	thought.VoiceID = nil

	return &thought, nil
}

func (r *ThoughtsRepo) UpdateThought(ctx context.Context, req *models.UpdateThoughtReq) error {
	// Use only fields that exist in DB schema
	builder := QB.Update("thoughts")

	// Update content if provided
	if req.Content != nil {
		builder = builder.Set("content", *req.Content)
		// If content is provided but voice_text is not explicitly set,
		// and voice_text is currently empty, update voice_text with content
		// This handles the case where a voice thought is being edited
		if req.VoiceText == nil {
			// Use SQL CASE to update voice_text only if it's currently NULL or empty
			builder = builder.Set("voice_text", sq.Expr("CASE WHEN voice_text IS NULL OR voice_text = '' THEN ? ELSE voice_text END", *req.Content))
		}
	}

	// Update voice_text if explicitly provided
	if req.VoiceText != nil {
		builder = builder.Set("voice_text", *req.VoiceText)
	}

	// Update other fields if provided
	if req.SentimentLabel != nil {
		builder = builder.Set("sentiment_label", req.SentimentLabel)
	}
	if req.SentimentScore != nil {
		builder = builder.Set("sentiment_score", req.SentimentScore)
	}
	if req.TypeThought != nil {
		builder = builder.Set("type_thought", req.TypeThought)
	}

	// Always update minio_id when image_id is in the request
	// Frontend always sends image_id (even if null), so we always update it
	// If ImageID is nil (null in JSON), set minio_id to NULL
	// If ImageID is provided, set minio_id to that value
	if req.ImageID != nil && *req.ImageID != "" {
		// ImageID is provided and not empty - set minio_id to that value
		builder = builder.Set("minio_id", *req.ImageID)
	} else if req.ImageID != nil {
		// ImageID is explicitly set to null - set minio_id to NULL using SQL NULL
		// Use sq.Expr to properly set NULL in PostgreSQL
		builder = builder.Set("minio_id", sq.Expr("NULL"))
	}

	sql, args, _ := builder.Where(sq.Eq{"thought_id": req.ThoughtID}).ToSql()

	// Log SQL for debugging
	if req.ImageID != nil {
		println(fmt.Sprintf("[UpdateThought] SQL: %s, args: %v, image_id: %s", sql, args, *req.ImageID))
	} else {
		println(fmt.Sprintf("[UpdateThought] SQL: %s, args: %v, image_id: NULL", sql, args))
	}

	_, err := r.db.Exec(ctx, sql, args...)
	if err != nil {
		println(fmt.Sprintf("[UpdateThought] Error: %v", err))
		return err
	}

	println(fmt.Sprintf("[UpdateThought] Successfully updated thought_id=%d", req.ThoughtID))
	return nil
}

func (r *ThoughtsRepo) GetByID(ctx context.Context, thoughtID, userID int64) (*models.Thought, error) {
	// Use only fields that exist in DB schema
	sql, args, _ := QB.Select("thought_id", "user_id", "created_at", "content", "voice_text", "sentiment_label", "sentiment_score", "type_thought", "minio_id").
		From("thoughts").Where(sq.Eq{"thought_id": thoughtID, "user_id": userID}).ToSql()
	var t models.Thought
	var content *string
	var voiceText *string
	var typeThought *string
	var minioID *string
	err := r.db.QueryRow(ctx, sql, args...).Scan(&t.ThoughtID, &t.UserID, &t.CreatedAt, &content, &voiceText, &t.SentimentLabel, &t.SentimentScore, &typeThought, &minioID)
	if err != nil {
		return nil, err
	}
	t.Content = content
	t.VoiceText = voiceText
	t.TypeThought = typeThought
	t.ImageID = minioID // Map minio_id from DB to ImageID in model

	// Log for debugging
	if minioID != nil {
		println(fmt.Sprintf("[GetByID] Retrieved thought_id=%d, minio_id=%s", thoughtID, *minioID))
	} else {
		println(fmt.Sprintf("[GetByID] Retrieved thought_id=%d, minio_id=NULL", thoughtID))
	}

	t.SubmittedAt = nil
	t.VoiceID = nil
	return &t, nil
}

func (r *ThoughtsRepo) ListByUserID(ctx context.Context, userID int64, limit int) ([]*models.Thought, error) {
	// Use only fields that exist in DB schema
	sql, args, _ := QB.Select("thought_id", "user_id", "created_at", "content", "voice_text", "sentiment_label", "sentiment_score", "type_thought", "minio_id").
		From("thoughts").Where(sq.Eq{"user_id": userID}).
		OrderBy("created_at DESC").Limit(uint64(limit)).ToSql()
	rows, err := r.db.Query(ctx, sql, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var thoughts []*models.Thought
	for rows.Next() {
		var t models.Thought
		var content *string
		var voiceText *string
		var typeThought *string
		var minioID *string
		if err := rows.Scan(&t.ThoughtID, &t.UserID, &t.CreatedAt, &content, &voiceText, &t.SentimentLabel, &t.SentimentScore, &typeThought, &minioID); err != nil {
			return nil, err
		}
		t.Content = content
		t.VoiceText = voiceText
		t.TypeThought = typeThought
		t.ImageID = minioID // Map minio_id from DB to ImageID in model
		t.SubmittedAt = nil
		t.VoiceID = nil
		thoughts = append(thoughts, &t)
	}
	return thoughts, rows.Err()
}

func (r *ThoughtsRepo) ListByUserIDAndDateRange(ctx context.Context, userID int64, startDate, endDate interface{}) ([]*models.Thought, error) {
	// Use only fields that exist in DB schema
	sql, args, _ := QB.Select("thought_id", "user_id", "created_at", "content", "voice_text", "sentiment_label", "sentiment_score", "type_thought", "minio_id").
		From("thoughts").
		Where(sq.Eq{"user_id": userID}).
		Where(sq.GtOrEq{"created_at": startDate}).
		Where(sq.LtOrEq{"created_at": endDate}).
		OrderBy("created_at DESC").ToSql()
	rows, err := r.db.Query(ctx, sql, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var thoughts []*models.Thought
	for rows.Next() {
		var t models.Thought
		var content *string
		var voiceText *string
		var typeThought *string
		var minioID *string
		if err := rows.Scan(&t.ThoughtID, &t.UserID, &t.CreatedAt, &content, &voiceText, &t.SentimentLabel, &t.SentimentScore, &typeThought, &minioID); err != nil {
			return nil, err
		}
		t.Content = content
		t.VoiceText = voiceText
		t.TypeThought = typeThought
		t.ImageID = minioID // Map minio_id from DB to ImageID in model
		t.SubmittedAt = nil
		t.VoiceID = nil
		thoughts = append(thoughts, &t)
	}
	return thoughts, rows.Err()
}

func (r *ThoughtsRepo) DeleteByID(ctx context.Context, thoughtID int64) error {
	sql, args, _ := QB.Delete("thoughts").Where(sq.Eq{"thought_id": thoughtID}).ToSql()
	_, err := r.db.Exec(ctx, sql, args...)
	return err
}
